import test from 'node:test';import assert from 'node:assert/strict';
import {EVENT,TABLES,TEST_CASES} from '../revision-2026/js/config.js';
import {createDraft,setQuantity,setGuests,syncResponsible,totals,attendees,personErrors,duplicates,toPayload,escapeHTML,csvCell} from '../revision-2026/js/domain.js';
import {validateBooking,amountCOP,testFlag,paymentStatus} from '../supabase/functions/_shared/validation.mjs';
import {sha256,equalHex} from '../supabase/functions/_shared/crypto.mjs';
function complete(){const d=createDraft();d.responsible={firstName:'Persona',lastName:'Ejemplo',email:'prueba@example.com',phone:'3001234567'};d.members.forEach((p,i)=>Object.assign(p,{firstName:'Socio '+i,lastName:'Ejemplo',action:'0001'}));d.visitors.forEach((p,i)=>Object.assign(p,{firstName:'Invitado '+i,lastName:'Ejemplo',document:'10000000'+i,email:'prueba@example.com',phone:'3001234567'}));d.table=12;d.terms=true;syncResponsible(d);return d;}
test('45 mesas sin duplicados, Rialto 1-33 y Lobby 34-45',()=>{assert.equal(TABLES.length,45);assert.equal(new Set(TABLES.map(t=>t.number)).size,45);assert.equal(TABLES.filter(t=>t.zone==='Rialto').length,33);assert.equal(TABLES.filter(t=>t.zone==='Lobby').length,12);});
test('las coordenadas permanecen dentro del mapa',()=>TABLES.forEach(t=>{assert.ok(t.x>0&&t.x<100&&t.y>0&&t.y<100);}));
test('precios corresponden al protocolo',()=>{assert.equal(EVENT.memberPrice,180000);assert.equal(EVENT.guestPrice,260000);});
test('8 socios totalizan 1440000',()=>assert.equal(totals(createDraft()).total,1440000));
test('5 socios y 3 invitados totalizan 1680000',()=>{const d=createDraft();setGuests(d,3);assert.equal(totals(d).total,1680000);});
test('todas las combinaciones de 8 a 10 asistentes mantienen la suma',()=>{for(const n of [8,9,10])for(let g=0;g<=n;g++){const d=createDraft();d.responsibleAttends=false;setQuantity(d,n);setGuests(d,g);const t=totals(d);assert.equal(t.members+t.guests,n);assert.equal(t.total,(n-g)*180000+g*260000);}});
test('no permite 7,11 o cantidades fraccionarias',()=>{for(const n of [7,11,8.5,NaN])assert.throws(()=>setQuantity(createDraft(),n));});
test('responsable socio siempre conserva un cupo dentro del grupo',()=>{const d=createDraft();setGuests(d,8);assert.equal(d.guests,7);assert.equal(d.quantity,8);});
test('responsable invitado conserva un cupo',()=>{const d=createDraft();d.responsibleType='guest';syncResponsible(d);assert.equal(d.guests,1);});
test('ajustar cantidad no elimina nombres ya escritos',()=>{const d=complete();setQuantity(d,10);d.members[9].firstName='Nombre conservado';setQuantity(d,8);setQuantity(d,10);assert.equal(d.members[9].firstName,'Nombre conservado');});
test('modificar distribucion no elimina datos de invitados',()=>{const d=complete();setGuests(d,2);d.visitors[1].firstName='Conservar';setGuests(d,0);setGuests(d,2);assert.equal(d.visitors[1].firstName,'Conservar');});
test('responsable se autocompleta sin cambiar accion',()=>{const d=complete();d.members[0].action='101';d.responsible.firstName='Nuevo';syncResponsible(d);assert.equal(d.members[0].firstName,'Nuevo');assert.equal(d.members[0].action,'101');});
test('socios de una familia pueden compartir accion',()=>{const d=complete();assert.equal(duplicates(d),false);assert.doesNotThrow(()=>validateBooking(toPayload(d)));});
test('invitados con documento repetido son rechazados',()=>{const d=complete();setGuests(d,2);d.terms=true;d.visitors[1].document=d.visitors[0].document;assert.equal(duplicates(d),true);assert.throws(()=>validateBooking(toPayload(d)));});
test('campos incompletos no pasan la validacion',()=>{assert.ok(personErrors({firstName:'A'},'member').length>0);assert.throws(()=>validateBooking({}));});
test('datos completos pasan la validacion del servidor',()=>{const d=complete();setGuests(d,3);d.terms=true;assert.equal(validateBooking(toPayload(d)).attendees.length,8);});
test('manipular total del navegador no altera el payload validado',()=>{const body={...toPayload(complete()),amount:1,price:1,role:'admin',environment:'live'};const clean=validateBooking(body);assert.equal(clean.amount,undefined);assert.equal(clean.role,undefined);assert.equal(clean.environment,undefined);});
test('validacion independiente exige todos los asistentes',()=>{const b=toPayload(complete());b.attendees.pop();assert.throws(()=>validateBooking(b));});
test('sin condiciones aceptadas no pasa',()=>{const b=toPayload(complete());b.acceptedTerms=false;assert.throws(()=>validateBooking(b));});
test('documentos malformados son rechazados',()=>{const d=complete();setGuests(d,1);d.terms=true;d.visitors[0].document='<script>';assert.throws(()=>validateBooking(toPayload(d)));});
test('XSS se representa como texto',()=>assert.equal(escapeHTML('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
test('exportacion neutraliza formulas CSV',()=>{assert.ok(csvCell('=2+2').startsWith('"\''));assert.ok(csvCell('  @SUM(A1)').startsWith('"\''));assert.equal(csvCell('Normal'),'"Normal"');});
test('cuatro importes de prueba autorizados',()=>assert.deepEqual(TEST_CASES.map(t=>t.amount),[1000,1500,3000,5500]));
test('importes de ePayco se comparan exactamente en COP',()=>{assert.equal(amountCOP('5500.00'),5500);for(const s of ['5500.50','1e3','5,500','-1000','NaN','1000abc','Infinity'])assert.throws(()=>amountCOP(s));});
test('el modo de prueba no se deduce de un valor ausente',()=>{assert.equal(testFlag('TRUE'),true);assert.equal(testFlag('false'),false);assert.throws(()=>testFlag(undefined));});
test('los estados conocidos se clasifican; los demas requieren revision',()=>{assert.equal(paymentStatus('Aceptada'),'approved');assert.equal(paymentStatus('Pendiente'),'pending');assert.equal(paymentStatus('Rechazada'),'declined');assert.equal(paymentStatus('Reversada'),'review');});
test('SHA256 y comparacion de firmas rechazan manipulaciones',async()=>{const hash=await sha256('abc');assert.equal(hash,'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');assert.ok(equalHex(hash,hash.toUpperCase()));assert.equal(equalHex(hash,'0'.repeat(64)),false);assert.equal(equalHex('',''),false);});
