import test from 'node:test';
import assert from 'node:assert/strict';
import { createHandler, BUILD } from '../supabase/functions/_shared/confirmation-handler.mjs';
import { normalizeDetail, queryDetail, VerificationError } from '../supabase/functions/_shared/epayco-detail.mjs';
import { sha256 } from '../supabase/functions/_shared/crypto.mjs';
import { HttpError } from '../supabase/functions/_shared/http.ts';
const REF='9001001', MERCHANT='12345', INVOICE='BN26TEST-3119e18d06ef43408530bc5b6e760571';
const ID='c004da43-a61e-44c8-bf34-020e5d9eff0f';
const env={EPAYCO_P_CUST_ID_CLIENTE:MERCHANT,EPAYCO_P_KEY:'fixture-only-not-a-key',EPAYCO_PUBLIC_KEY:'fixture-public',EPAYCO_PRIVATE_KEY:'fixture-private',BN_PAYMENTS_MODE:'test'};
const secret=k=>{if(!env[k])throw new HttpError(503,'missing');return env[k];};
function detail(state='Rechazada'){return {success:true,data:{referencePayco:Number(REF),amount:1000,currency:'COP',status:state,test:'1',bill:INVOICE,log:{x_ref_payco:Number(REF),x_cust_id_cliente:Number(MERCHANT),x_transaction_id:REF,x_amount:'1000.00',x_currency_code:'COP',x_response:state,x_test_request:'TRUE',x_id_invoice:INVOICE,x_id_factura:INVOICE}}};}
function canonical(state='Rechazada'){return normalizeDetail(detail(state),REF,MERCHANT);}
function deps(extra={}){const writes=[];let queries=0;const dependencies={secret,queryDetail:async()=>{queries++;return canonical();},adminIdentity:async()=>({id:'admin-fixture'}),rateLimit:async()=>{},db:async path=>path.startsWith('bn_events')?[{environment:'test'}]:[{id:ID,event_id:ID,invoice:INVOICE,amount:1000,status:'payment_pending'}],rpc:async(name,args)=>{writes.push({name,args});return {status:args.p_status==='approved'?'confirmed':args.p_status};},...extra};return {handler:createHandler(dependencies),writes,queries:()=>queries};}
async function notification(extra={}){const data={x_ref_payco:REF,x_transaction_id:REF,x_amount:'1000',x_currency_code:'COP',x_id_invoice:INVOICE,x_response:'Rechazada',...extra};data.x_signature=await sha256([MERCHANT,env.EPAYCO_P_KEY,data.x_ref_payco,data.x_transaction_id,data.x_amount,data.x_currency_code].join('^'));return data;}
const post=(body,headers={})=>new Request('https://example.invalid/hook',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
test('authenticated detail normalizes numeric strings and decimal COP',()=>{assert.deepEqual(canonical(),{reference:REF,merchant:MERCHANT,transaction:REF,invoice:INVOICE,amount:1000,currency:'COP',isTest:true,status:'declined'});});
for(const [name,payload] of [['empty object',{}],['HTTP 200 error object',{status:false,data:{status:'error'}}],['null',null],['array',[]],['missing log',{success:true,data:{}}]])test('incomplete provider response is not merchant mismatch: '+name,()=>{assert.throws(()=>normalizeDetail(payload,REF,MERCHANT),e=>e instanceof VerificationError&&e.status===503&&!e.code.includes('MISMATCH'));});
for(const [name,change,code] of [
 ['wrong reference',d=>d.data.referencePayco=222,'REFERENCE_MISMATCH'],['wrong merchant',d=>d.data.log.x_cust_id_cliente=999,'MERCHANT_MISMATCH'],['wrong amount',d=>d.data.log.x_amount='1','AMOUNT_MISMATCH'],['wrong currency',d=>d.data.log.x_currency_code='USD','CURRENCY_MISMATCH'],['wrong invoice',d=>d.data.log.x_id_invoice='elsewhere','INVOICE_MISMATCH'],['inconsistent test',d=>d.data.log.x_test_request='FALSE','ENVIRONMENT_MISMATCH'],['missing state',d=>delete d.data.status,'PROVIDER_STATUS_MISSING'],['missing test',d=>delete d.data.test,'PROVIDER_ENVIRONMENT_MISSING'],['stale log',d=>d.data.log.x_response='Aceptada','PROVIDER_STATE_INCONSISTENT'],['missing merchant',d=>delete d.data.log.x_cust_id_cliente,'PROVIDER_MERCHANT_MISSING']])test('rejects '+name,()=>{const d=detail();change(d);assert.throws(()=>normalizeDetail(d,REF,MERCHANT),e=>e.code===code);});
test('unknown state is review, never approved',()=>assert.equal(canonical('Unknown status').status,'review'));
test('APIFY read uses numeric reference and documented GET body',async()=>{const calls=[];const t=async(...args)=>{calls.push(args);return calls.length===1?{token:'fixture-token-not-a-secret-123'}:detail();};await queryDetail(REF,secret,t);assert.deepEqual(calls[1].slice(0,3),['/transaction/detail','GET',{filter:{referencePayco:9001001}}]);assert.equal(calls[0][0],'/login');});
test('rejected APIFY authentication cannot be used',async()=>{await assert.rejects(queryDetail(REF,secret,async()=>({success:false})),e=>e.code==='PROVIDER_LOGIN_INVALID');});
test('health never reads secrets or writes',async()=>{const d=deps({secret:()=>{throw Error('no');}});const r=await d.handler(new Request('https://example.invalid/hook?health=1'));assert.equal((await r.json()).build,BUILD);assert.equal(d.writes.length,0);});
test('missing signature 400',async()=>{const d=deps();assert.equal((await d.handler(post({}))).status,400);assert.equal(d.queries(),0);});
test('false signature 401 before provider read',async()=>{const d=deps();const b=await notification();b.x_signature='0'.repeat(64);assert.equal((await d.handler(post(b))).status,401);assert.equal(d.queries(),0);});
test('legacy diagnostic false signature still 401',async()=>{const d=deps();const b={x_ref_payco:'BN_DIAGNOSTIC_NO_PAYMENT',x_transaction_id:'NO_TRANSACTION',x_amount:'1000',x_currency_code:'COP',x_signature:'0'.repeat(64)};assert.equal((await d.handler(post(b))).status,401);});
test('malformed JSON is 400, not 503',async()=>{const d=deps();const r=await d.handler(new Request('https://example.invalid',{method:'POST',headers:{'content-type':'application/json'},body:'{bad'}));assert.equal(r.status,400);});
test('duplicate query parameters rejected',async()=>{const d=deps();assert.equal((await d.handler(new Request('https://example.invalid?x_ref_payco=1&x_ref_payco=2'))).status,400);});
test('authentic callback reconciles decline, never confirms',async()=>{const d=deps();const r=await d.handler(post(await notification()));assert.equal(r.status,200);assert.equal(d.writes[0].args.p_status,'declined');});
test('GET callback accepted securely',async()=>{const d=deps();const query=new URLSearchParams(await notification());assert.equal((await d.handler(new Request('https://example.invalid?'+query))).status,200);});
test('URL encoded POST callback accepted',async()=>{const d=deps();const query=new URLSearchParams(await notification());const r=await d.handler(new Request('https://example.invalid',{method:'POST',body:query}));assert.equal(r.status,200);});
test('forged incoming approval ignored; authenticated state wins',async()=>{const d=deps();const b=await notification({x_response:'Aceptada'});await d.handler(post(b));assert.equal(d.writes[0].args.p_status,'declined');});
test('valid incoming signature not enough for different transaction',async()=>{const d=deps({queryDetail:async()=>({...canonical(),transaction:'DIFFERENT'})});assert.equal((await d.handler(post(await notification()))).status,400);assert.equal(d.writes.length,0);});
test('incomplete response cannot cause any write',async()=>{const d=deps({queryDetail:async()=>normalizeDetail({status:false,data:{status:'error'}},REF,MERCHANT)});const r=await d.handler(post(await notification()));assert.equal(r.status,503);assert.equal(d.writes.length,0);});
test('live payment rejected by test function',async()=>{const d=deps({queryDetail:async()=>({...canonical(),isTest:false})});assert.equal((await d.handler(post(await notification()))).status,400);assert.equal(d.writes.length,0);});
test('live environment does not perform query',async()=>{const d=deps({secret:k=>k==='BN_PAYMENTS_MODE'?'live':secret(k)});assert.equal((await d.handler(post(await notification()))).status,503);assert.equal(d.queries(),0);});
const reconcile={action:'reconcile',reference:REF,reservationId:ID};
test('reconcile unauthenticated blocked',async()=>{const d=deps({adminIdentity:async()=>{throw new HttpError(401,'login');}});assert.equal((await d.handler(post(reconcile))).status,401);assert.equal(d.queries(),0);});
test('reconcile unauthorized role blocked',async()=>{const d=deps({adminIdentity:async()=>{throw new HttpError(403,'role');}});assert.equal((await d.handler(post(reconcile))).status,403);assert.equal(d.queries(),0);});
test('admin gets authoritative state; supplied approved ignored',async()=>{const d=deps();const r=await d.handler(post({...reconcile,status:'approved'}));assert.equal(r.status,200);assert.equal((await r.json()).status,'declined');});
test('reconcile other invoice blocked',async()=>{const d=deps({queryDetail:async()=>({...canonical(),invoice:'BN26TEST-other'})});assert.equal((await d.handler(post(reconcile))).status,400);assert.equal(d.writes.length,0);});
test('reconcile other amount blocked',async()=>{const d=deps({queryDetail:async()=>({...canonical(),amount:3000})});assert.equal((await d.handler(post(reconcile))).status,400);assert.equal(d.writes.length,0);});
test('commercial reservation blocked before query',async()=>{const d=deps({db:async p=>p.startsWith('bn_events')?[{environment:'live'}]:[{id:ID,event_id:ID,invoice:INVOICE,amount:1000}]});assert.equal((await d.handler(post(reconcile))).status,403);assert.equal(d.queries(),0);});
test('reconcile throttling preserved',async()=>{const d=deps({rateLimit:async()=>{throw new HttpError(429,'rate');}});assert.equal((await d.handler(post(reconcile))).status,429);assert.equal(d.queries(),0);});
test('duplicate callback delegates atomic idempotency',async()=>{let count=0;const d=deps({rpc:async()=>{count++;return {duplicate:true,status:'declined'};}});const b=await notification();for(let i=0;i<2;i++)assert.equal((await d.handler(post(b))).status,200);assert.equal(count,2);});
test('approvals must be provider verified',async()=>{const d=deps({queryDetail:async()=>canonical('Aceptada')});const r=await d.handler(post(await notification()));assert.equal((await r.json()).status,'confirmed');assert.equal(d.writes[0].args.p_test,true);});
