import {icon} from './icons.js';
import {CONFIG,TABLES,TEST_CASES} from './config.js';
import {money,escapeHTML as e,csvCell} from './domain.js';
import {api,login,logout,session} from './api.js';
const $=id=>document.getElementById(id);
let demo=false,tab='dashboard',query='',data=null,selectedTest='T5500';
const stateLabels={confirmed:'Confirmada',payment_pending:'En pago',held:'Retenida',opening:'Preparando',expired:'Vencida',declined:'Rechazada',review:'Por revisar',cancelled:'Cancelada'};
function sample(){
 const numbers=[1,2,4,7,8,10,13,15,18,22,27,34];
 const reservations=numbers.map((n,i)=>({id:`DEMO-${String(i+1).padStart(3,'0')}`,invoice:`DEMO-${String(i+1).padStart(3,'0')}`,table_number:n,status:i<8?'confirmed':i<11?'payment_pending':'declined',responsible_name:`Responsable de ejemplo ${String(i+1).padStart(2,'0')}`,quantity:i%3===0?10:8,member_count:i%3===0?7:6,guest_count:i%3===0?3:2,amount:i%3===0?2040000:1600000,created_at:'2026-10-02T15:30:00-05:00'}));
 const active=reservations.filter(r=>['confirmed','payment_pending'].includes(r.status));
 return {reservations,tables:TABLES.map(t=>({...t,status:active.find(r=>r.table_number===t.number)?.status==='confirmed'?'occupied':active.find(r=>r.table_number===t.number)?'held':'available'})),settings:{mode:'test',keysConfigured:false},legacyCount:0,source:'demo'};
}
function showLogin(message=''){
 $('logout').hidden=true;
 $('admin-root').innerHTML=`<section class="form-card login-card"><div class="login-emblem">${icon("lock")}</div><span class="overline">ACCESO PRIVADO</span><h1>Administraci&oacute;n de Eventos</h1><p class="subtext">Reservas, mesas, asistentes y seguimiento de pagos en un solo lugar.</p>${message?`<div class="error-box" role="alert">${e(message)}</div>`:''}<form id="login-form"><div class="fields"><div class="field"><label for="username">Usuario</label><input id="username" name="username" autocomplete="username" value="EventosyServicios" required></div><div class="field"><label for="password">Contrase&ntilde;a</label><input id="password" name="password" type="password" autocomplete="current-password" required></div></div><p id="login-error" class="error-box" role="alert" hidden></p><button type="submit" class="button primary full" id="login-button">Ingresar</button></form>${CONFIG.preview?'<div class="notice-box">El acceso real se habilita al configurar Supabase Auth. La demostraci&oacute;n no necesita contrase&ntilde;a y solo muestra datos ficticios.</div><button type="button" class="text-button" id="demo-button">Ver demostraci&oacute;n del administrador</button>':''}</section>`;
 $('login-form').addEventListener('submit',async ev=>{ev.preventDefault();if(CONFIG.preview){$('login-error').textContent='Esta entrega est\u00e1 en vista previa. Usa la demostraci\u00f3n; no ingreses contrase\u00f1as reales.';$('login-error').hidden=false;return;}$('login-button').disabled=true;try{await login($('username').value,$('password').value);await load();}catch(err){$('login-error').textContent=err.message;$('login-error').hidden=false;}finally{if($('login-button'))$('login-button').disabled=false;}});
 $('demo-button')?.addEventListener('click',()=>{demo=true;data=sample();render();});
}
function summary(){
 const confirmed=data.reservations.filter(r=>r.status==='confirmed'),held=data.reservations.filter(r=>['held','opening','payment_pending'].includes(r.status));
 return {confirmed:confirmed.length,held:held.length,available:data.tables.filter(t=>t.status==='available').length,booked:confirmed.reduce((n,r)=>n+r.quantity,0),members:confirmed.reduce((n,r)=>n+r.member_count,0),guests:confirmed.reduce((n,r)=>n+r.guest_count,0),revenue:confirmed.reduce((n,r)=>n+r.amount,0),pending:held.reduce((n,r)=>n+r.amount,0)};
}
function kpi(label,value,note,featured=false,kind="grid"){return `<article class="kpi ${featured?'featured':''}"><div class="kpi-top"><small>${label}</small><span class="kpi-icon">${icon(kind)}</span></div><strong>${value}</strong><p>${note}</p></article>`;}
function dashboard(){const s=summary();return `<div class="kpi-grid">${kpi('Reservas confirmadas',s.confirmed,`${s.booked} asistentes confirmados`,false,'check')}${kpi('Mesas disponibles',s.available,`De ${data.tables.length} mesas configuradas`)}${kpi('Solicitudes en pago',s.held,'No se cuentan como venta confirmada',false,'clock')}${kpi(demo?'Pagos ficticios aprobados':'Pagos de prueba aprobados',money(s.revenue),demo?'Ejemplo visual, no es recaudo real':'Simulaciones, no es dinero recibido',true,'credit')}</div><div class="admin-two-col"><section class="admin-card"><div class="admin-card-title"><span class="section-index">${icon("grid")}</span><h2>Ocupaci&oacute;n de mesas</h2><button type="button" class="text-button" data-tab="tables">Ver mesas ${icon("arrow")}</button></div><p>Disponibilidad exclusiva del evento seleccionado, sin mezclar el hist&oacute;rico.</p><div class="occupancy-track"><span class="confirmed" style="width:${s.confirmed/data.tables.length*100}%"></span><span class="held" style="width:${s.held/data.tables.length*100}%"></span></div><div class="occupancy-legend"><span><i class="dot"></i> ${s.confirmed} confirmadas</span><span><i class="dot held"></i> ${s.held} en pago</span><span>${s.available} disponibles</span></div><div class="metric-list"><div><span>Cupos en mesas totalmente disponibles</span><strong>${s.available*10}</strong></div><div><span>Puestos confirmados de socios / corporados</span><strong>${s.members}</strong></div><div><span>Puestos confirmados de invitados</span><strong>${s.guests}</strong></div></div><p class="small muted" style="margin-top:16px">Los puestos sobrantes en una mesa confirmada no se ofrecen autom&aacute;ticamente a otro grupo.</p></section><section class="admin-card"><div class="admin-card-title"><span class="section-index">${icon("credit")}</span><h2>Control de pagos</h2></div><p>Una solicitud pendiente no confirma una mesa.</p><div class="metric-list"><div><span>Valor de solicitudes pendientes</span><strong>${money(s.pending)}</strong></div><div><span>Rechazadas / vencidas</span><strong>${data.reservations.filter(r=>['declined','expired'].includes(r.status)).length}</strong></div><div><span>Incidencias por revisar</span><strong>${data.reservations.filter(r=>r.status==='review').length}</strong></div></div><div class="notice-box">El modo de esta versi&oacute;n es <strong>PRUEBAS</strong>. No habilita cobros reales.</div></section></div>`;}
function reservationRows(){const rows=data.reservations.filter(r=>[r.invoice,r.responsible_name,r.table_number,stateLabels[r.status]].join(' ').toLowerCase().includes(query.toLowerCase()));return rows.length?rows.map(r=>`<tr><td>${e(r.invoice)}</td><td>${e(r.responsible_name)}</td><td>${r.table_number}</td><td>${r.quantity}</td><td><span class="badge ${e(r.status)}">${e(stateLabels[r.status]||r.status)}</span></td><td>${money(r.amount)}</td><td><button type="button" class="text-button" data-detail="${e(r.id)}">Ver detalle</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty-state">No hay reservas que coincidan con la b&uacute;squeda.</td></tr>';}
function reservations(){return `<section class="admin-card"><div class="table-toolbar"><div><h2>Reservas y solicitudes</h2><p class="small muted">${demo?'Registros ficticios de demostraci&oacute;n.':'Hasta 500 registros. No incluye el hist&oacute;rico anterior.'}</p></div><button type="button" class="button secondary" id="export-csv">Exportar CSV</button></div><div class="table-toolbar"><input type="search" class="search-input" id="reservation-search" placeholder="Buscar por responsable, mesa o referencia" aria-label="Buscar reservas" value="${e(query)}"></div><div class="table-scroll"><table class="data-table"><thead><tr><th>REFERENCIA</th><th>RESPONSABLE</th><th>MESA</th><th>PERSONAS</th><th>ESTADO</th><th>VALOR</th><th></th></tr></thead><tbody id="reservation-rows">${reservationRows()}</tbody></table></div></section>`;}
function tablePanel(){return `<section class="admin-card"><h2>Las 45 mesas del plano 2026</h2><p>Vista administrativa. Esta versi&oacute;n no permite liberar manualmente una mesa con un pago pendiente.</p><div class="legend" style="margin:18px 0"><span><i class="dot"></i> Disponible</span><span><i class="dot held"></i> En pago</span><span><i class="dot occupied"></i> Confirmada</span></div>${['Rialto','Lobby'].map(zone=>`<h3>${zone}</h3><div class="table-grid">${data.tables.filter(t=>t.zone===zone).map(t=>`<button type="button" class="table-cell ${t.status}" data-table-detail="${t.number}" title="Mesa ${t.number}">${t.number}<small>${t.status==='available'?'Libre':t.status==='held'?'En pago':'Reservada'}</small></button>`).join('')}</div>`).join('')}</section>`;}
function tests(){return `<section class="admin-card"><h2>Laboratorio de pagos</h2><p>Solo administradores. Usa mesas y reservas de ensayo separadas del evento real.</p><div class="test-grid">${TEST_CASES.map(t=>`<button type="button" class="test-option ${t.code===selectedTest?'active':''}" data-test="${t.code}"><small>PRUEBA ${t.code.slice(1)}</small><strong>${money(t.amount)}</strong></button>`).join('')}</div><div class="notice-box"><strong>No utiliza dinero real.</strong> El total de ensayo lo impone el servidor a partir del caso elegido. Cambiar el importe en el navegador no cambia el cobro.</div><a class="button primary" href="index.html?test_case=${selectedTest}">Abrir formulario de ensayo &#8599;</a><div class="connection-list"><div><span>Modo del servidor</span><strong>${demo?'Demostraci&oacute;n':'Pruebas'}</strong></div><div><span>Llaves de ePayco</span><strong>${demo?'Sin comprobar':data.settings.keysConfigured?'Configuradas':'Pendientes'}</strong></div><div><span>Datos de tarjetas en el formulario</span><strong>No se solicitan</strong></div><div><span>Activaci&oacute;n de cobros reales</span><strong>Deshabilitada</strong></div></div></section>`;}
function history(){return `<section class="admin-card"><h2>Hist&oacute;rico anterior</h2><p>La actualizaci&oacute;n no borra ni renombra las tablas originales.</p>${demo?'<div class="notice-box">La demostraci&oacute;n no consulta reservas privadas anteriores.</div>':`<div class="notice-box">${data.legacyCount} registros conservados en la tabla original. La clasificaci&oacute;n por evento debe revisarse antes de una migraci&oacute;n definitiva; la fecha de creaci&oacute;n por s&iacute; sola no demuestra a qu&eacute; evento pertenece una reserva.</div><button class="button secondary" type="button" id="load-history">Consultar registros hist&oacute;ricos</button><div id="history-results"></div>`}</section>`;}
function render(){
 $('logout').hidden=false;$('admin-banner').hidden=false;$('admin-banner').innerHTML=demo?'<strong>DEMOSTRACI&Oacute;N VISUAL</strong> &middot; Todos los registros y valores de este panel son ficticios.':'<strong>ENTORNO DE PRUEBAS</strong> &middot; No mezclar estos valores con el recaudo real del evento.';
 $('admin-root').innerHTML=`<div class="admin-page"><div class="admin-heading"><div><span class="overline">EVENTOS Y SERVICIOS <span class="admin-heading-tag">CONTROL 2026</span></span><h1>Todo tu evento,<br>en un solo lugar.</h1><p>Fiesta Blanco y Negro &middot; 6 de noviembre de 2026</p></div><div class="admin-actions"><button type="button" class="button secondary" id="refresh-admin">Actualizar</button><a href="index.html" class="button primary">Ver formulario &#8599;</a></div></div><nav class="admin-tabs" aria-label="Secciones administrativas">${[['dashboard','Resumen','grid'],['reservations','Reservas','list'],['tables','Mesas','people'],['tests','Pruebas ePayco','lab'],['history','Hist&oacute;rico','history']].map(([id,name,i])=>`<button type="button" data-tab="${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}>${icon(i)}${name}</button>`).join('')}</nav><div id="admin-content">${({dashboard,reservations,tables:tablePanel,tests,history}[tab])()}</div></div>`;
 $('refresh-admin').addEventListener('click',()=>demo?render():load());
 $('reservation-search')?.addEventListener('input',ev=>{query=ev.target.value;$('reservation-rows').innerHTML=reservationRows();});
 $('export-csv')?.addEventListener('click',()=>{const lines=[['Referencia','Responsable','Mesa','Personas','Socios','Invitados','Estado','Valor COP'],...data.reservations.map(r=>[r.invoice,r.responsible_name,r.table_number,r.quantity,r.member_count,r.guest_count,stateLabels[r.status],r.amount])];const blob=new Blob(['\uFEFF'+lines.map(row=>row.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(demo?'DEMOSTRACION-':'PRUEBAS-')+'reservas-2026.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('load-history')?.addEventListener('click',async()=>{try{const h=await api('history',{},true);$('history-results').innerHTML=`<div class="table-scroll" style="margin-top:20px"><table class="data-table"><thead><tr><th>REGISTRO</th><th>RESPONSABLE</th><th>MESA</th><th>CANTIDAD</th><th>ESTADO ORIGINAL</th><th>CREACI&Oacute;N</th></tr></thead><tbody>${h.rows.map(r=>`<tr><td>${e(r.id.slice(0,8))}</td><td>${e(r.responsable)}</td><td>${r.mesa_id}</td><td>${r.cantidad}</td><td>${e(r.estado)}</td><td>${e(r.created_at.slice(0,10))}</td></tr>`).join('')}</tbody></table></div>`;}catch(err){$('history-results').textContent=err.message;}});
}
async function load(){try{data=await api('admin',{},true);demo=false;render();}catch(err){showLogin(err.message);}}
function detail(title,body){$('admin-dialog-title').textContent=title;$('admin-dialog-body').innerHTML=body;$('admin-dialog').showModal();}
document.addEventListener('click',async ev=>{
 const b=ev.target.closest('button');if(!b)return;
 if(b.dataset.tab){tab=b.dataset.tab;render();}
 if(b.dataset.test){selectedTest=b.dataset.test;render();}
 if(b.dataset.detail){const r=data.reservations.find(x=>x.id===b.dataset.detail);if(!r)return;let people=[];if(!demo){try{people=(await api('detail',{id:r.id},true)).attendees;}catch(err){detail('No se pudo consultar',`<p>${e(err.message)}</p>`);return;}}detail(`Mesa ${r.table_number}`,`<p><strong>${e(r.responsible_name)}</strong></p><p>${e(r.invoice)} &middot; ${stateLabels[r.status]}</p><p>${r.quantity} asistentes &middot; ${money(r.amount)}</p>${demo?'<div class="notice-box">Registro ficticio. No contiene datos personales reales.</div>':`<div class="table-scroll"><table class="data-table"><tbody>${people.map(p=>`<tr><td>${e(p.first_name)} ${e(p.last_name)}</td><td>${e(p.kind==='member'?'Socio':'Invitado')}</td></tr>`).join('')}</tbody></table></div>`}`);}
 if(b.dataset.tableDetail){const t=data.tables.find(t=>t.number===Number(b.dataset.tableDetail));detail(`Mesa ${t.number} \u00b7 ${t.zone}`,`<p>Capacidad m\u00e1xima: ${t.capacity} puestos.</p><p>Estado: ${t.status==='available'?'Disponible':t.status==='held'?'En proceso de pago':'Confirmada'}.</p><p class="muted small">Los cambios de ocupaci\u00f3n se realizan al validar pagos. No se libera una mesa con transacci\u00f3n pendiente desde esta pantalla.</p>`);}
});
$('close-detail').addEventListener('click',()=>$('admin-dialog').close());
$('logout').addEventListener('click',async()=>{if(!demo)await logout();demo=false;data=null;$('admin-banner').hidden=true;showLogin();});
if(!CONFIG.preview&&session())load();else showLogin();
